import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed w-full h-screen bg-gray-200 ">
        <Sidebar />
        <div className="flex flex-col w-full h-full ml-64 p-4">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
